name: Python application test

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Add PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV
    - name: Run tests
      run: |
        pytest
      continue-on-error: true
